name: Copy v1-uk-docs dir to v1-uk-docs-release branch and v1-eu-docs dir to v1-eu-docs-release branch

on:
  push:
    branches:
      - master

jobs:
  copy-v1-uk-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Copy v1-uk-docs to Temp Directory
      run: |
        mkdir -p temp-v1-uk-docs
        cp -r v1-uk-docs/* temp-v1-uk-docs/

    - name: Prepare v1-uk-docs-release Branch
      run: |
        git fetch origin +refs/heads/v1-uk-docs-release:refs/remotes/origin/v1-uk-docs-release
        git checkout v1-uk-docs-release || git checkout --orphan v1-uk-docs-release

    - name: Copy from Temp Directory to v1-uk-docs-release
      run: |
        cp -r temp-v1-uk-docs/* .
        git add .
        git commit -m "Copy v1-uk-docs to root of v1-uk-docs-release"

    - name: Push to v1-uk-docs-release
      run: |
        git push origin v1-uk-docs-release

  copy-v1-eu-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Copy v1-eu-docs to Temp Directory
      run: |
        mkdir -p temp-v1-eu-docs
        cp -r v1-eu-docs/* temp-v1-eu-docs/

    - name: Prepare v1-eu-docs-release Branch
      run: |
        git fetch origin +refs/heads/v1-eu-docs-release:refs/remotes/origin/v1-eu-docs-release
        git checkout v1-eu-docs-release || git checkout --orphan v1-eu-docs-release

    - name: Copy from Temp Directory to v1-eu-docs-release
      run: |
        cp -r temp-v1-eu-docs/* .
        git add .
        git commit -m "Copy v1-eu-docs to root of v1-eu-docs-release"

    - name: Push to v1-eu-docs-release Branch
      run: |
        git push origin v1-eu-docs-release
